import PDFDocument from "pdfkit";
import { PassThrough } from "stream";

/**
 * Convert summary object to Markdown string
 */
export function summaryToMarkdown(summary) {
  let md = `# ${summary.title}\n\n`;

  if (summary.overview) {
    md += `## Overview\n\n${summary.overview}\n\n`;
  }

  if (summary.key_concepts?.length > 0) {
    md += `## Key Concepts\n\n`;
    summary.key_concepts.forEach((concept) => {
      md += `- ${concept}\n`;
    });
    md += "\n";
  }

  if (summary.vocabulary?.length > 0) {
    md += `## Vocabulary\n\n`;
    summary.vocabulary.forEach(({ term, definition }) => {
      md += `**${term}:** ${definition}\n\n`;
    });
  }

  if (summary.common_mistakes?.length > 0) {
    md += `## Common Mistakes\n\n`;
    summary.common_mistakes.forEach((mistake) => {
      md += `- ⚠ ${mistake}\n`;
    });
    md += "\n";
  }

  if (summary.exercises?.length > 0) {
    md += `## Practice Exercises\n\n`;
    summary.exercises.forEach((exercise, i) => {
      md += `${i + 1}. ${exercise}\n\n`;
    });
  }

  return md;
}

/**
 * Convert summary object to PDF stream
 */
export function summaryToPDF(summary) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        font: "Helvetica",
      });

      const stream = new PassThrough();
      doc.pipe(stream);

      // Title
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(summary.title, { align: "left" });
      doc.moveDown(0.5);

      // Overview
      if (summary.overview) {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text("Overview", { underline: true });
        doc.moveDown(0.2);
        doc
          .fontSize(11)
          .font("Helvetica")
          .text(summary.overview, { align: "justify" });
        doc.moveDown(0.8);
      }

      // Key Concepts
      if (summary.key_concepts?.length > 0) {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text("Key Concepts", { underline: true });
        doc.moveDown(0.2);
        doc.fontSize(11).font("Helvetica");
        summary.key_concepts.forEach((concept) => {
          doc.text(`• ${concept}`);
        });
        doc.moveDown(0.8);
      }

      // Vocabulary
      if (summary.vocabulary?.length > 0) {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text("Vocabulary", { underline: true });
        doc.moveDown(0.2);
        doc.fontSize(10).font("Helvetica");
        summary.vocabulary.forEach(({ term, definition }) => {
          doc.font("Helvetica-Bold").text(term, { continued: true });
          doc.font("Helvetica").text(`: ${definition}`);
          doc.moveDown(0.1);
        });
        doc.moveDown(0.4);
      }

      // Common Mistakes
      if (summary.common_mistakes?.length > 0) {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text("Common Mistakes", { underline: true });
        doc.moveDown(0.2);
        doc.fontSize(11).font("Helvetica");
        summary.common_mistakes.forEach((mistake) => {
          doc.text(`⚠ ${mistake}`);
        });
        doc.moveDown(0.8);
      }

      // Exercises
      if (summary.exercises?.length > 0) {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .text("Practice Exercises", { underline: true });
        doc.moveDown(0.2);
        doc.fontSize(11).font("Helvetica");
        summary.exercises.forEach((exercise, i) => {
          doc.text(`${i + 1}. ${exercise}`);
          doc.moveDown(0.3);
        });
      }

      // Footer
      doc.moveDown(1);
      doc
        .fontSize(9)
        .fillColor("#888888")
        .text(`Generated by AsideMe • ${new Date().toLocaleString()}`, {
          align: "center",
        });

      doc.end();

      stream.on("finish", () => {
        resolve(stream);
      });

      doc.on("error", reject);
      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
}

// ── Quiz exporters ────────────────────────────────────────────────────────────

/**
 * Convert quiz result ({ questions: [{q, options, answer, explanation}] })
 * into a Markdown study sheet.
 */
export function quizToMarkdown(quiz, { title = "Quiz" } = {}) {
  const questions = quiz?.questions || [];
  let md = `# ${title}\n\n`;
  md += `> ${questions.length} question${questions.length === 1 ? "" : "s"} · generated by AsideMe\n\n`;
  md += `---\n\n## Questions\n\n`;
  questions.forEach((q, i) => {
    md += `### ${i + 1}. ${q.q || ""}\n\n`;
    (q.options || []).forEach((opt) => {
      md += `- ${opt}\n`;
    });
    md += `\n`;
  });
  md += `---\n\n## Answer Key\n\n`;
  questions.forEach((q, i) => {
    md += `**${i + 1}.** ${q.answer || "—"}`;
    if (q.explanation) md += ` — ${q.explanation}`;
    md += `\n\n`;
  });
  return md;
}

/**
 * Convert quiz result to a PDF stream.
 */
export function quizToPDF(quiz, { title = "Quiz" } = {}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50, font: "Helvetica" });
      const stream = new PassThrough();
      doc.pipe(stream);

      doc.fontSize(24).font("Helvetica-Bold").text(title);
      doc.moveDown(0.3);
      const questions = quiz?.questions || [];
      doc
        .fontSize(10)
        .fillColor("#666666")
        .text(
          `${questions.length} question${questions.length === 1 ? "" : "s"} · generated by AsideMe`,
        );
      doc.fillColor("black");
      doc.moveDown(0.8);

      doc.fontSize(12).font("Helvetica-Bold").text("Questions", { underline: true });
      doc.moveDown(0.4);
      questions.forEach((q, i) => {
        doc.fontSize(11).font("Helvetica-Bold").text(`${i + 1}. ${q.q || ""}`);
        doc.moveDown(0.2);
        doc.fontSize(11).font("Helvetica");
        (q.options || []).forEach((opt) => {
          doc.text(`   ${opt}`);
        });
        doc.moveDown(0.6);
      });

      doc.addPage();
      doc.fontSize(12).font("Helvetica-Bold").text("Answer Key", { underline: true });
      doc.moveDown(0.4);
      doc.fontSize(11).font("Helvetica");
      questions.forEach((q, i) => {
        doc.font("Helvetica-Bold").text(`${i + 1}. ${q.answer || "—"}`, { continued: !!q.explanation });
        if (q.explanation) {
          doc.font("Helvetica").text(` — ${q.explanation}`);
        }
        doc.moveDown(0.3);
      });

      doc.moveDown(1);
      doc
        .fontSize(9)
        .fillColor("#888888")
        .text(`Generated by AsideMe • ${new Date().toLocaleString()}`, { align: "center" });

      doc.end();
      stream.on("finish", () => resolve(stream));
      doc.on("error", reject);
      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
}

// ── Flashcards exporters ──────────────────────────────────────────────────────

/**
 * Convert flashcards result ({ cards: [{front, back}] }) into Markdown.
 */
export function flashcardsToMarkdown(flashcards, { title = "Flashcards" } = {}) {
  const cards = flashcards?.cards || [];
  let md = `# ${title}\n\n`;
  md += `> ${cards.length} card${cards.length === 1 ? "" : "s"} · generated by AsideMe\n\n`;
  md += `---\n\n`;
  cards.forEach((c, i) => {
    md += `### Card ${i + 1}\n\n`;
    md += `**Front:** ${c.front || ""}\n\n`;
    md += `**Back:** ${c.back || ""}\n\n`;
    md += `---\n\n`;
  });
  return md;
}

/**
 * Convert flashcards result to a PDF stream — one card per "block" with a
 * clean front/back layout that prints well for cut-out study cards.
 */
export function flashcardsToPDF(flashcards, { title = "Flashcards" } = {}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 50, font: "Helvetica" });
      const stream = new PassThrough();
      doc.pipe(stream);

      doc.fontSize(24).font("Helvetica-Bold").text(title);
      doc.moveDown(0.3);
      const cards = flashcards?.cards || [];
      doc
        .fontSize(10)
        .fillColor("#666666")
        .text(`${cards.length} card${cards.length === 1 ? "" : "s"} · generated by AsideMe`);
      doc.fillColor("black");
      doc.moveDown(0.8);

      cards.forEach((c, i) => {
        doc.fontSize(11).font("Helvetica-Bold").text(`Card ${i + 1}`);
        doc.moveDown(0.2);
        doc.fontSize(11).font("Helvetica-Bold").text("Front: ", { continued: true });
        doc.font("Helvetica").text(c.front || "");
        doc.moveDown(0.15);
        doc.fontSize(11).font("Helvetica-Bold").text("Back: ", { continued: true });
        doc.font("Helvetica").text(c.back || "");
        doc.moveDown(0.6);
      });

      doc.moveDown(1);
      doc
        .fontSize(9)
        .fillColor("#888888")
        .text(`Generated by AsideMe • ${new Date().toLocaleString()}`, { align: "center" });

      doc.end();
      stream.on("finish", () => resolve(stream));
      doc.on("error", reject);
      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
}
